name: autshift
version: "0.1.0"
license: "GPL-2.0-or-later"
date: 2022-02-16
description: |
    Algorithms for Automotphisms of the Shift and related objects

authors:
    - name: Luke Elliott
      url: https://le27.github.io/Luke-Elliott/

maintainers:
    - name: Luke Elliott
      url: https://le27.github.io/Luke-Elliott/

GAP: ">=4.8.0"

needed-pkgs:
    - name: "automata"
      version: ">=0.0.0"
      url: "https://gap-packages.github.io/automata/"
    - name: "digraphs"
      version: ">=0.15.0"
      url: "https://digraphs.github.io/Digraphs"
    - name: "fr"
      version: ">=2.4.6"
      url: "https://gap-packages.github.io/fr"
    - name: "aaa"
      version: ">=0.0.0"
      url: "https://gap-packages.github.io/aaa"
    - name: "datastructures"
      version: ">= 0.2.5"
      url: "https://gap-packages.github.io/datastructures"

www: https://gap-packages.github.io/autshift
readme: README.md
packageinfo: https://gap-packages.github.io/autshift/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/autshift/releases/download/v0.1.0/autshift-0.1.0.tar.gz

abstract: |
    The <span class="pkgname">autshift</span> package, is a package for    building and using transducers as described in the paper entitled    'Automata, Dynamical Systems, and Groups' of R. I. Grigorchuk,    V. V. Nekrashevich, and V. I. Sushchanskii. Previous similar packages    such as <span class="pkgname">fr</span> and    <span class="pkgname">AutomGrp</span> have had a focus on synchronous    transducers. Hence the name <span class="pkgname">autshift</span> which    stands for "asynchronous automata algorithms".

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Ell22</span>]   <b class='BibAuthor'>Elliott, L.</b>,
     <i class='BibTitle'>autshift, Algorithms for Automotphisms of the Shift and related objects,
             Version 0.1.0</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/autshift">https://gap-packages.github.io/autshift</a></span>.
    </p>
    

bibtex: |
    @misc{ autshift0.1.0,
      author =           {Elliott, L.},
      title =            {{autshift},  Algorithms  for Automotphisms of the Shift and related objects,
                          {V}ersion 0.1.0},
      month =            {Feb},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href                              {https://gap-packages.github.io/autshift}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{autshift}}},
      printedkey =       {Ell22}
    }

